@echo Mailer automatico sogegross...

@echo Eseguo i task giornalieri...
call winhttpjs.bat  http://localhost/webContab/my/php/dailyTasks.php -saveTo c:\dailyTasks.txt

@echo Fatto tutto! Esco
rem set /p DUMMY=Hit PREMI INVIO PER USCIRE...