@REM Backup script generated by Areca v7.5 on 26-nov-2020 16.02

@chcp 1252
@REM Incremental backup
@REM Target Group : "workspace"
@REM Target : "BACKUPCOMPLETO"
@"C:/Programmi/Areca/areca_cl.exe" backup -c -wdir "C:\DOCUME~1\Server\IMPOST~1\Temp\tmp-Server" -config "C:/Documents and Settings/Server/.areca/workspace/1012179447.bcfg"

