@REM Backup script generated by Areca v7.5 on 12-nov-2023 16.34

@chcp 1252
@REM Full backup
@REM Target Group : "workspace"
@REM Target : "BACKUPCOMPLETO"
@"C:/areca-7.5/areca_cl.exe" backup -f -c -wdir "C:\DOCUME~1\Posto1\IMPOST~1\Temp\tmp-Posto1" -config "C:/Documents and Settings/Posto1/.areca/workspace/1012179447.bcfg"

