<style>
body{
	padding:2em;
	font-size:0.7em;
	font-family:Helvetica, sans-serif
	
}
table{
	width:100%;
	
}
table, td{
	font-size:1em;	
}
.finePagina {page-break-after: always;}
.titoloSezione{
	/*background-color:#e3e3e3;*/
	box-shadow:inset 0 0 0 1000px #e3e3e3;
	padding:0.6em;
	font-size:1.2em;
	font-family:Helvetica, sans-serif
}
.dataCorso{
	/*background-color:#e3e3e3;*/
	box-shadow:inset 0 0 0 1000px #e3e3e3;
	padding:1em;
	
}
.titoloCorso{
	/*background-color:#e3e3e3;*/
	box-shadow:inset 0 0 0 1000px #e3e3e3;
	padding:1em;
	
}

/*hide page titles and number*/
@page { size: auto;  margin: 0mm; }
</style>

<?php
$dati=
"DESCRIZIONE CORSO		CORSO TEORICO PRATICO DI ANTINCENDIO ED EVAQUAZIONE PER ADDETTI ALLA SQUADRA DI EMERGENZA
TIPO CORSO				SQUADRA ANTINCENDIO
RIFERIMENTO NORMATIVO	ART.13 DLGS 626/94, DM 10/03/1998
DURATA ORE				8
ENTE ORGANIZZATORE		SALUTE E SICUREZZA SRL
VALIDITA ANNI			-
DATA INIZIO				24/03/1999
DATA FINE				24/03/1999
 ZAMBOTTO GIUSEPPE
 FOGGINI RUDY
***************************************************************************
DESCRIZIONE CORSO		CORSO TEORICO PRATICO DI PRIMO SOCCORSO PER ADDETTI ALLA SQUADRA DI PRIMO INTERVENTO IN AZIENDA
TIPO CORSO				SQUADRA PRIMO SOCCORSO
RIFERIMENTO NORMATIVO	DLGS 626/94 CAPO III, EX ART 4,12,15 COMMI 1-4, DM 388/03
DURATA ORE				-
ENTE ORGANIZZATORE		SALUTE E SICUREZZA SRL
VALIDITA ANNI			-
DATA INIZIO				22/04/1999
DATA FINE				24/04/1999
 MURARI LAURA
 FILIPI MARA
 BRUN TIZIANA
***************************************************************************
DESCRIZIONE CORSO		RIUNIONE DI FORMAZIONE DEI DIPENDENTI IN MATERIA DI IGIENE DEI PRODOTTI ALIMENTARI
TIPO CORSO				FORMAZIONE GENERICA
RIFERIMENTO NORMATIVO	DLGS 26/05/1997 N.155
DURATA ORE				-
ENTE ORGANIZZATORE		SALUTE E SICUREZZA SRL
VALIDITA ANNI			-
DATA INIZIO				10/09/1999
DATA FINE				10/09/1999
 FILIPI MARA
 BRUN TIZIANA
 BONADIMANI MARA
 LAVAGNINI GABRIELLA
 RIGONI RITA MARIA
 MANTOVANI ROSANNA
 PASQUALO MARIA TERESA
 MURARI PAOLA
 CALMERO SIMONETTA
 ZANCOPE NICOLETTA
 BRUNELLI ELEONORA
 GIRLANDA ERICA
 MURARI LAURA
 GIORGINI AURELIA
 BRUN GENNI
***************************************************************************
DESCRIZIONE CORSO		CONDUZIONE ED USO DEL CARRELLO ELEVATORE IN SICUREZZA
TIPO CORSO				ABILITAZIONE CARRELLO
RIFERIMENTO NORMATIVO	ART.38 DLGS 626/94, DLGS 242/96, DLGS 359/99
DURATA ORE				8
ENTE ORGANIZZATORE		TRIMEC 
VALIDITA ANNI			-
DATA INIZIO				19/01/2002
DATA FINE				26/01/2002
 MURARI LAURA
 FILIPPI MARA
***************************************************************************
DESCRIZIONE CORSO		IGIENE E SICUREZZA SUI LUOGHI DI LAVORO
TIPO CORSO				FOMAZIONE GENERICA
RIFERIMENTO NORMATIVO	DLGS 626/94, DM 10/03/1998
DURATA ORE				2
ENTE ORGANIZZATORE		SALUTE E SICUREZZA SRL
VALIDITA ANNI			-
DATA INIZIO				27/06/2003
DATA FINE				27/06/2003
 BONADIMARI MARA
 FILIPI MARA
 CALMERO SIMONETTA
 MURARI LAURA
 TAKTOUR FATIMA
 BRUN TIZIANA
 MURARI PAOLA
 RIGONI RITA MARIA
 TAKTOUR AICHA
 CRISAN RODICA ILEANA
 TOPPAR REBECCA
 STELLINI IRENE
 GIRLANDA ERIKA
 BRUN ANGIOLINA
 FOGGINI RUDY
 MANTOVANI GIULIANO
 BRUN GENNI
 BELKHADIR HANAN
 JOUIED MINA
 CIUMACENCO LUDMILA
 CIUMACENCO IGOR
 TAKTOUR MILOUDA
 IKIKER NAJIA
 EL HAOUZY FATIMA
 SREMAC SONJA
 RADAK VESNA
 OUALLAL ZAHRA
 BRUN LISA
 EL GORSI SAMIRA
 ZUCCOTTO VANIA
 ZAMBOTTO GIUSEPPE
 BRUM DEBORA
 ACCORDI ANNA PAOLA
***************************************************************************
DESCRIZIONE CORSO		CORSO TEORICO PRATICO DI PRONTO SOCCORSO PER ADDETTI ALLA SQUADRA DI PRIMO INTERVENTO IN AZIENDA
TIPO CORSO				SQUADRA PRIMO SOCCORSO
RIFERIMENTO NORMATIVO	DLGS 626/94 CAPO III, EX ART 4,12,15 COMMI 1-4, DM 388/03
DURATA ORE				-
ENTE ORGANIZZATORE		SALUTE E SICUREZZA SRL
VALIDITA ANNI			-
DATA INIZIO				15/07/2004
DATA FINE				16/07/2004
 BRUN TIZIANA
 FILIPPI MARA
 MURARI LAURA
***************************************************************************
DESCRIZIONE CORSO		ADDETTO ALLA PRODUZIONE E VENDITA DELLE SOSTANZE ALIMENTARI - CORSO LIBRETTO SANITARIO
TIPO CORSO				MANIPOLAZIONE ALIMENTI
RIFERIMENTO NORMATIVO	LEGGE REGIONALE 41 DEL 23/12/2003
DURATA ORE				-
ENTE ORGANIZZATORE		ULSS22
VALIDITA ANNI			-
DATA INIZIO				27/11/2006
DATA FINE				27/11/2006
PARTECIPANTI
 BRUN GENNI
 BRUN LISA
 TRIF IOANA MARIA
***************************************************************************
DESCRIZIONE CORSO		CORSO TEORICO PRATICO DI PRIMO SOCCORSO PER ADDETTI ALLA SQUADRA DI PRIMO INTERVENTO IN AZIENDA
TIPO CORSO				SQUADRA PRIMO SOCCORSO
RIFERIMENTO NORMATIVO	ART.13 DLGS 626/94 E DLGS 388/03
DURATA ORE				16
VALIDITA ANNI			-
ENTE ORGANIZZATORE		SALUTE E SICUREZZA SRL
DATA INIZIO				13/06/2007
DATA FINE				22/06/2007
 BRUN LISA
***************************************************************************
DESCRIZIONE CORSO		CORSO DI INFORMAZIONE E FORMAZIONE PER IL RESPONSABILE DEL SERVIZIO DI PREVENZIONE E PROTEZIONE
TIPO CORSO				RSPP
RIFERIMENTO NORMATIVO	DLGS 626/94 CAPO III EX ART. 4,12 E 15 COMMI 1-4, DLGS 242/96 DLGS 195/03
DURATA ORE				16
ENTE ORGANIZZATORE		SALUTE E SICUREZZA SRL
VALIDITA ANNI			-
DATA INIZIO				19/06/2007
DATA FINE				28/06/2007
PARTECIPANTI
 BRUN GIONNI
 BRUN GIMMI
***************************************************************************
DESCRIZIONE CORSO		CORSO INTERNO NORME DI COMPORTAMENTO SULLA CORRETTA PREPARAZIONE/MANIPOLAZIONE SICURA DEGLI ALIMENTI
TIPO CORSO				MANIPOLAZIONE ALIMENTI
RIFERIMENTO NORMATIVO	ART.14 LEGGE 283/1962
DURATA ORE				-
ENTE ORGANIZZATORE		LA FAVORITA DI BRUN G. E G. SRL UNIPERSONALE
VALIDITA ANNI			-
DATA INIZIO				04/03/2008
DATA FINE				04/03/2008
PARTECIPANTI
 BRUN MARISA
 BRUN TIZIANA
***************************************************************************
DESCRIZIONE CORSO		I CONCETTI GENERALI DELLA PREVENZIONE E I DPI
TIPO CORSO				FORMAZIONE GENERICA
RIFERIMENTO NORMATIVO	-
DURATA ORE				-
ENTE ORGANIZZATORE		PORTO 626
VALIDITA ANNI			-
DATA INIZIO				01/02/2009
DATA FINE				01/02/2009
PARTECIPANTI
 BRUN GIONNI
 CIUMACENCO IGOR
 ZAMBOTTO GIUSEPPE
 BRUM DEBORA
 BRUN MARISA
 TRIF IOANA MARIA
 BRUN GENNI
 BRUN LISA
***************************************************************************
DESCRIZIONE CORSO		FORMAZIONE E INFORMAZIONE DEI LAVORATORI SULLA SICUREZZA
TIPO CORSO				FORMAZIONE GENERICA
RIFERIMENTO NORMATIVO	D.LGS 81/2008
DURATA ORE				2
ENTE ORGANIZZATORE		LA FAVORITA DI BRUN G. E G. SRL UNIPESONALE
VALIDITA ANNI			-
DATA INIZIO				13/02/2009
DATA FINE				13/02/2009
PARTECIPANTI
 BRUN GIORGIO
 BRUN GIONNI
 BRUN GIMMI
 CIUMACENCO IGOR
 ZAMBOTTO GIUSEPPE
 BRUM DEBORA
 BRUN GENNI
 BRUN LISA
 BRUN MARISA
 TRIF IOANA MARIA
***************************************************************************
DESCRIZIONE CORSO		CORSO DI FORMAZIONE PER RAPPRESENTANTE DEI LAVORATORI PER LA SICUREZZA - R.L.S.
TIPO CORSO				RLS
RIFERIMENTO NORMATIVO	ART.37 COMMA 11 DLGS 81/08
DURATA ORE				32
ENTE ORGANIZZATORE		ARTEC PROGETTI SAS
VALIDITA ANNI			-
DATA INIZIO				15/05/2009
DATA FINE				10/07/2009
PARTECIPANTI
 BRUM DEBORA
***************************************************************************
DESCRIZIONE CORSO		ADDETTO ALLA PRODUZIONE E VENDITA DELLE SOSTANZE ALIMENTARI
TIPO CORSO				MANIPOLAZIONE ALIMENTI
RIFERIMENTO NORMATIVO	LEGGE REGIONALE 41 DEL 23/12/2003
DURATA ORE				-
ENTE ORGANIZZATORE		ULSS22
VALIDITA ANNI			-
DATA INIZIO				21/12/2009
DATA FINE				21/12/2009
PARTECIPANTI
 TRIF IOANA MARIA
 BRUN GENNI
 BRUN LISA
***************************************************************************
DESCRIZIONE CORSO		ADDETTO ALLA PRODUZIONE E VENDITA DELLE SOSTANZE ALIMENTARI
TIPO CORSO				MANIPOLAZIONE ALIMENTI
RIFERIMENTO NORMATIVO	LEGGE REGIONALE 41 DEL 23/12/2003
DURATA ORE				-
ENTE ORGANIZZATORE		ULSS22
VALIDITA ANNI			-
DATA INIZIO				24/05/2010
DATA FINE				24/05/2010
PARTECIPANTI
 BRUN MARISA
***************************************************************************
DESCRIZIONE CORSO		ADDETTI ALLA SQUADRA ANTINCENDIO - RISCHIO MEDIO
TIPO CORSO				SQUADRA ANTINCENDIO
RIFERIMENTO NORMATIVO	ART.46 DLGS 81/08, DM 10/03/1998
DURATA ORE				8
ENTE ORGANIZZATORE		ARTEC PROGETTI SAS
VALIDITA ANNI			-
DATA INIZIO				12/06/2012
DATA FINE				15/06/2012
 BRUN GIONNI
 BRUN LISA
***************************************************************************
DESCRIZIONE CORSO		ADDETTO ALLA SQUADRA DI PRIMO SOCCORSO AZIENDALE
TIPO CORSO				SQUADRA PRIMO SOCCORSO
RIFERIMENTO NORMATIVO	DLGS 09/04/2008 N.81 E SUCC.MODIFICHE ED INTEGRAZIONI, DECRETO MINISTERIALE N.388 DEL 15/07/2003
DURATA ORE				6
ENTE ORGANIZZATORE		ARTEC PROGETTI SAS
VALIDITA ANNI			3
DATA INIZIO				29/03/2012
DATA FINE				29/03/2012
 BRUN LISA
***************************************************************************
DESCRIZIONE CORSO		ADDETTO ALLA PRODUZIONE E VENDITA DELLE SOSTANZE ALIMENTARI
TIPO CORSO				MANIPOLAZIONE ALIMENTI
RIFERIMENTO NORMATIVO	-
DURATA ORE				3
ENTE ORGANIZZATORE		ENAIP VENETO
VALIDITA ANNI			-
DATA INIZIO				23/04/2013
DATA FINE				23/04/2013
PARTECIPANTI
 TRIF IOANA MARIA
 BRUN GENNI
 BRUN LISA
 BRUN MARISA
 BRUN TIZIANA
***************************************************************************
DESCRIZIONE CORSO		AGGIORNAMENTO ADDETTI ALLA SQUADRA ANTINCENDIO - RISCHIO MEDIO
TIPO CORSO				SQUADRA ANTINCENDIO
RIFERIMENTO NORMATIVO	ART.37 E 46 DLGS 81/08, DM 10/03/1998, CIRCOLARE DEI VIGILI DEL FUOCO DEL 23/02/2011
DURATA ORE				5
ENTE ORGANIZZATORE		ARTEC PROGETTI SAS
VALIDITA ANNI			-
DATA INIZIO				16/07/2015
DATA FINE				17/07/2015
 BRUN GIONNI
 BRUN LISA
***************************************************************************
DESCRIZIONE CORSO		CORSO INTERNO SULLE BUONE PRATICHE E NORME DI COMPORTAMENTO PER LA PREPARAZIONE E MNAIPOLAZIONE DEGLI ALIMENTI
TIPO CORSO				MANIPOLAZIONE ALIMENTI
RIFERIMENTO NORMATIVO	LEGGE REGIONALE 19/03/2013 N.2 ART.5
DURATA ORE				-
ENTE ORGANIZZATORE		LA FAVORITA DI BRUN G. E G. SRL UNIPERSONALE
VALIDITA ANNI			-
DATA INIZIO				01/10/2015
DATA FINE				01/10/2015
 SANDU RODICA
 CALMERO SIMONETTA
 MIRON VIORICA
 TAKTOUR FATIMA
 TAKTOUR AICHA
 IKIKER NAJIA
 BUCATA ANA MARIA
 BRUN GRETA
 DARDOVA VERONIKA
 FOGGINI RUDY
 ETTAOUFI ELKERBIRA
 BADOUI IMANE
 EL HAOUZY FATIMA
 MURARI LAURA

***************************************************************************
DESCRIZIONE CORSO		ADDETTO ALLA SQUADRA DI PRIMO SOCCORSO AZIENDALE
TIPO CORSO				SQUADRA PRIMO SOCCORSO
RIFERIMENTO NORMATIVO	DLGS 09/04/2008 N.81 E SUCC.MODIFICHE ED INTEGRAZIONI, DECRETO MINISTERIALE N.388 DEL 15/07/2003
DURATA ORE				6
ENTE ORGANIZZATORE		ARTEC PROGETTI SAS
VALIDITA ANNI			3
DATA INIZIO				26/11/2015
DATA FINE				26/11/2015
 BRUN LISA
***************************************************************************
DESCRIZIONE CORSO		ATTESTATO DI ABILITAZIONE - AGGIORNAMENTO FORMAZIONE PER LA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI
TIPO CORSO				ABILITAZIONE MACCHINE AGRICOLE
RIFERIMENTO NORMATIVO	ART.73 COMMA 5 D.LGS 81/08 E S.M.I. - ALLEGATO VIII ACCORDO STATO REGIONI  22/02/2012
DURATA ORE				4
ENTE ORGANIZZATORE		AGRICOLTORI VERONA SERVIZI SRL
VALIDITA ANNI			-
DATA INIZIO				29/03/2016
DATA FINE				29/03/2016
PARTECIPANTI
 FOGGINI RUDY
 BRUN GIMMI
***************************************************************************
DESCRIZIONE CORSO		ABILITAZIONE ALLA CONDUZIONE DI CARELLI ELEVATORI SEMOVENTI INDUSTRIALI
TIPO CORSO				ABILITAZIONE CARRELLO
RIFERIMENTO NORMATIVO	ART.73 COMMA 5 DLGS 81/08, ACCORDO STATO REGIONI DEL 22/02/2012
DURATA ORE				12
ENTE ORGANIZZATORE		FESICA CONFSAL - CONFSAL FISALS(PER TRAMITE SALUTE E SICUREZZA SRL)
VALIDITA ANNI			-
DATA INIZIO				07/05/2018
DATA FINE				08/05/2018
 MURARI LAURA
 BRUN GIMMI
 BONIARDI MATTEO
 BRUN GIAMPAOLO
 CIUMACENCO IGOR
 FOGGINI RUDY
 BRUN GIONNI
***************************************************************************
DESCRIZIONE CORSO		IGIENE E SICUREZZA SUL LAVORO CORSO DI INFOMAZIONE E FORMAZIONE DEI LAVORATORI IN COLLABORAZIONE CON L'OPP
TIPO CORSO				FORMAZIONE GENERICA
RIFERIMENTO NORMATIVO	ART.36 E 37 DLGS 81/08; ACCORDO STATO REGIONI 21/12/2011
DURATA ORE				12
ENTE ORGANIZZATORE		SALUTE E SICUREZZA SRL
VALIDITA ANNI			-
DATA INIZIO				24/09/2018
DATA FINE				13/10/2018
PARTECIPANTI
 BONIARDI MATTEO
 BRUM DEBORA
 BRUN GENNI
 TRIF IOANA MARIA
 ZAMBOTTO GIUSEPPE
 CALMERO SIMONETTA
 DARDOVA VERONIKA
 FOGGINI RUDY
 NEZHA ONEDA
 TAKTOUR AICHA
 TAKTOUR FATIMA
 BRUN GIAMPAOLO
 BRUN LISA
 BRUN TIZIANA
***************************************************************************
DESCRIZIONE CORSO		IGIENE E SICUREZZA SUL LAVORO CORSO DI INFOMAZIONE E FORMAZIONE DEI LAVORATORI IN COLLABORAZIONE CON L'OPP
TIPO CORSO				FORMAZIONE GENERICA
RIFERIMENTO NORMATIVO	ART.36 E 37 DLGS 81/08; ACCORDO STATO REGIONI 21/12/2011
DURATA ORE				8
ENTE ORGANIZZATORE		SALUTE E SICUREZZA SRL
VALIDITA ANNI			-
DATA INIZIO				24/09/2018
DATA FINE				13/10/2018
PARTECIPANTI
 BRUN GIMMI
 GIANELLO FABIANA
 IKIKER NAJIA
***************************************************************************
DESCRIZIONE CORSO		IGIENE E SICUREZZA SUL LAVORO CORSO DI INFOMAZIONE E FORMAZIONE DEI LAVORATORI IN COLLABORAZIONE CON L'OPP
TIPO CORSO				FORMAZIONE GENERICA
RIFERIMENTO NORMATIVO	ART.36 E 37 DLGS 81/08; ACCORDO STATO REGIONI 21/12/2011
DURATA ORE				4
ENTE ORGANIZZATORE		SALUTE E SICUREZZA SRL
VALIDITA ANNI			-
DATA INIZIO				24/09/2018
DATA FINE				13/10/2018
PARTECIPANTI
 EL HAOUZY FATIMA
***************************************************************************
DESCRIZIONE CORSO		CORSO PER RESPONSABILE DEL SERVIZIO DI PREVENZIONE E PROTEZIONE - RISCHIO ALTO
TIPO CORSO				RSPP
RIFERIMENTO NORMATIVO	ART.34 DLGS N.81 09/04/2008; CONF.STATO REGIONI 21/12/2011; CONF.STATO REGIONI 25/07/2012
DURATA ORE				48
ENTE ORGANIZZATORE		ARTEC PROGETTI SAS
VALIDITA ANNI			5
DATA INIZIO				25/03/2020
DATA FINE				12/06/2020
PARTECIPANTI
 BRUN GIONNI
***************************************************************************
DESCRIZIONE CORSO		AGGIORNAMENTO - CORSO PER RAPPRESENTANTE DEI LAVORATORI PER LA SICUREZZA
TIPO CORSO				RLS
RIFERIMENTO NORMATIVO	ART.34 DLGS N.81 09/04/2008; 
DURATA ORE				4
ENTE ORGANIZZATORE		ARTEC PROGETTI SAS
VALIDITA ANNI			-
DATA INIZIO				25/03/2020
DATA FINE				17/04/2020
PARTECIPANTI
 BRUM DEBORA
***************************************************************************
DESCRIZIONE CORSO		FORMAZIONE E INFORMAZIONE DEI LAVORATORI SULLA SICUREZZA PARTE GENERALE
TIPO CORSO				FORMAZIONE GENERICA
RIFERIMENTO NORMATIVO	ART.36 E 37 D.LGS 81/2008 - ACCORDO STATO REGIONI 21/12/2011
DURATA ORE				4
ENTE ORGANIZZATORE		PREVENZIONE SUL LAVORO SRL STP
VALIDITA ANNI			-
DATA INIZIO				15/05/2023
DATA FINE				15/05/2023
PARTECIPANTI
 BRUN GIMMI
 BRUN MARISA
 CALIARI ILENIA
 CALIARI LARA
 CHHIBA FATIMA
 CIUMACENCO IGOR
 MAROCCHIO LORELLA
 MURARI LAURA
 OSADOLOR FAITH
 PARICHAT PHUESOONGNOEN
 TAGUYA LATIFA
***************************************************************************
DESCRIZIONE CORSO		ABILITAZIONE ALLA CONDUZIONE DI CARELLI ELEVATORI SEMOVENTI INDUSTRIALI (MODULO PRATICO)
TIPO CORSO				ABILITAZIONE CARRELLO
RIFERIMENTO NORMATIVO	ART.73 COMMA 5 DLGS 81/08, ACCORDO STATO REGIONI DEL 22/02/2012
DURATA ORE				4
ENTE ORGANIZZATORE		CONFSAL FISALS(PREVENZIONE SUL LAVORO SRL STP)
VALIDITA ANNI			-
DATA INIZIO				29/05/2023
DATA FINE				29/05/2023
 BRUN GIAMPAOLO
 BRUN GIMMI
 BRUN GIONNI
 MURARI LAURA
 FOGGINI RUDY
 IGOR CIUMACENCO
***************************************************************************
DESCRIZIONE CORSO		FORMAZIONE E INFORMAZIONE DEI LAVORATORI SULLA SICUREZZA PARTE SPECIFICA
TIPO CORSO				FORMAZIONE GENERICA
RIFERIMENTO NORMATIVO	ART.36 E 37 D.LGS 81/2008 - ACCORDO STATO REGIONI 21/12/2011
DURATA ORE				8
ENTE ORGANIZZATORE		PREVENZIONE SUL LAVORO SRL STP
VALIDITA ANNI			-
DATA INIZIO				05/06/2023
DATA FINE				12/06/2023
PARTECIPANTI
 BRUN MARISA
 CALIARI ILENIA
 CALIARI LARA
 CHHIBA FATIMA
 EL HAOUZY FATIMA
 MURARI LAURA
 OSADOLOR FAITH
 PARICHAT PHUESOONGNOEN
 TAGUYA LATIFA
***************************************************************************
DESCRIZIONE CORSO		FORMAZIONE E INFORMAZIONE DEI LAVORATORI SULLA SICUREZZA AGGIORNAMENTO
TIPO CORSO				FORMAZIONE GENERICA
RIFERIMENTO NORMATIVO	ART.36 E 37 D.LGS 81/2008 - ACCORDO STATO REGIONI 21/12/2011
DURATA ORE				8
ENTE ORGANIZZATORE		PREVENZIONE SUL LAVORO SRL STP
VALIDITA ANNI			-
DATA INIZIO				03/07/2023
DATA FINE				03/07/2023
PARTECIPANTI
 BONIARDI MATTEO
 BRUM DEBORA
 BRUN GENNI
 BRUN GIAMPAOLO
 BRUN TIZIANA
 CALMERO SIMONETTA
 FOGGINI RUDY
";

$datiDipendenti =
"ZAMBOTTO GIUSEPPE 				* 12/02/2008 * IMPIEGATO 					* 31/12/2019
BONIARDI MATTEO 				* 24/11/2015 * MAGAZZINIERE/CARRELLISTA		* 
BRUM DEBORA 					* 03/11/2008 * IMPIEGATA					* 
BRUN GENNI 						* 01/06/2009 * OPERAIA GENERICA CERNITRICE	* 
BRUN GIAMPAOLO 					* 05/09/2017 * CARRELLISTA/AUTISTA			* 
BRUN GIMMI 						* 20/04/2010 * AUTISTA						* 
BRUN LISA 						* 01/06/2009 * OPERAIA GENERICA CERNITRICE 	* 
BRUN MARISA 					* 04/03/2008 * OPERAIA GENERICA CERNITRICE	* 
BRUN TIZIANA 					* 06/10/2009 * OPERAIA GENERICA CERNITRICE	* 
CALMERO SIMONETTA 				* 01/10/2015 * OPERAIA CERNITRICE			* 
CIUMACENCO IGOR 				* 09/08/2004 * AUTISTA						* 
DARDOVA VERONIKA 				* 01/10/2015 * OPERAIA CERNITRICE			* 
EL HAOUZY FATIMA 				* 18/09/2017 * OPERAIA CERNITRICE			* 
FOGGINI RUDY 					* 01/10/2015 * CARRELLISTA/MAGAZZINIERE		* 
GIANELLO FABIANA 				* 04/09/2012 * OPERAIA GENERICA CERNITRIE	* 
NEZHA ONEDA 					* 08/09/2016 * OPERAIA GENERICA CERNITRIE	* 
TAKTOUR FATIMA 					* 03/04/2017 * OPERAIA GENERICA CERNITRIE	* 
TRIF IOANA MARIA 				* 09/06/2016 * OPERAIA GENERICA CERNITRIE	* 
ABOTCHI WOEWOE AMEYO VERONIQUE 	* 11/02/2019 * OPERAIA CERNITRICE			* 
EL GORSI NADIA 					* 12/02/2019 * OPERAIA CERNITRICE			* 
EL GORSI SAMIRA 				* 11/11/2019 * OPERAIA CERNITRICE			* 
TARGA RAIKA 					* 04/11/2019 * OPERAIA CERNITRICE			* 29/02/2020
NIZZARDO DANIELA 				* 05/02/2020 * OPERAIA CERNITRICE			* 
MAROCCHIO LORELLA 				* 05/02/2020 * OPERAIA CERNITRICE			* 
TAKTOUR AICHA 					* 01/10/2015 * OPERAIA CERNITRICE			* 31/01/2020
MURARI LAURA 					* 04/09/2017 * OPERAIA CERNITRICE			* 31/01/2020
IKIKER NAJIA 					* 01/07/2017 * OPERAIA CERNITRICE			* 31/01/2020
GOBBI MIRIA 					* 21/01/2020 * OPERAIA CERNITRICE			* 08/02/2020
EL YAZIDI SAIDA					* 05/11/2018 * OPERAIA CERNITRICE			* 31/05/2019
BRUN GIONNI						* 15/12/2001 * AMMINISTRATORE				* ";

//######################################################################################
//                     	DATI DIPENDENTI
//######################################################################################


$outDipendentiAssunti = array();
$outDipendentiLicenziati = array();
//FILTRA I DIPENDENTI CORRENTEMENTE ASSUNTI
$righeDipendenti = explode ( "\n" , $datiDipendenti);
foreach ($righeDipendenti as $rigaDipedente){
	$infoDipendente = explode ( "* " , $rigaDipedente);
	
	//se il dipendente non è già stato licenziato
	if($infoDipendente[3]==''){
		$outDipendentiAssunti[trim($infoDipendente[0])] = array();
		$outDipendentiAssunti[trim($infoDipendente[0])]['nome'] = trim($infoDipendente[0]);
		$outDipendentiAssunti[trim($infoDipendente[0])]['data assunzione'] = trim($infoDipendente[1]);
		$outDipendentiAssunti[trim($infoDipendente[0])]['mansione'] = trim($infoDipendente[2]);
		$outDipendentiAssunti[trim($infoDipendente[0])]['data licenziamento'] = trim($infoDipendente[3]);
	}else{
		$outDipendentiLicenziati[trim($infoDipendente[0])] = array();
		$outDipendentiLicenziati[trim($infoDipendente[0])]['nome'] = trim($infoDipendente[0]);
		$outDipendentiLicenziati[trim($infoDipendente[0])]['data assunzione'] = trim($infoDipendente[1]);
		$outDipendentiLicenziati[trim($infoDipendente[0])]['mansione'] = trim($infoDipendente[2]);
		$outDipendentiLicenziati[trim($infoDipendente[0])]['data licenziamento'] = trim($infoDipendente[3]);		
	}
}
//print_r($outDipendentiAssunti);
ksort($outDipendentiLicenziati);
ksort($outDipendentiAssunti);

//######################################################################################
//                     	DATI CORSI
//######################################################################################


$corsi = explode ( "***************************************************************************" , $dati);
$outCorsi=array();
$outDipendenti = array();
$i=0;
//print_r($corsi[1]);
foreach ($corsi as $corso){
	$outCorsi[$i]=array();
	$outCorsi[$i]['PARTECIPANTI']=array();
	$righe = explode ( "\n" , $corso);
	foreach ($righe as $riga){
		$chiavi=array(
		'DESCRIZIONE CORSO',
		'TIPO CORSO',
		'RIFERIMENTO NORMATIVO',
		'ENTE ORGANIZZATORE',
		'DURATA ORE',
		'VALIDITA ANNI',
		'DATA INIZIO',
		'DATA FINE',
		);
		foreach ($chiavi as $chiave){
			if(preg_match ( '/'.$chiave.'/' , $riga)){$outCorsi[$i][$chiave] = trim(str_replace($chiave,'',$riga));}
		}
		if(preg_match ( '/^ /' , $riga)){
			$outCorsi[$i]['PARTECIPANTI'][]=trim($riga);
			$outDipendenti[trim($riga)][] = &$outCorsi[$i];
		}
		//ordino i partecipanti alfabeticamente
		sort($outCorsi[$i]['PARTECIPANTI']);
	}
	$i++;	
}
//print_r($outCorsi);
//print_r($outDipendenti);

//######################################################################################
//                     	STAMPA
//######################################################################################
$outTxt = '';
//output
//foreach ($outDipendenti as $nome => $daticorsi){
foreach ($outDipendentiAssunti as $nome => $dipendenteAssunto){
	@$daticorsi =$outDipendenti[$nome]; 

	if(!array_key_exists($nome, $outDipendentiAssunti)){
		//se è già stato licenziato non lo stampo
		$outTxt.= '<br>Non stampato: '.$nome;
		@$outTxt.= ' Licenziato il : '.$outDipendentiLicenziati[$nome]['data licenziamento'];
		continue;
	}
	?>
	<br><br>
	<center>
		<h1>LBRETTO FORMATIVO DEL DIPENDENTE</h1>
		Redatto e mantenuto da <b>La Favorita di Brun G. e G. SRL Unip.</b>
		<br> Via Camagre n.38/B
		- 37063 Isola della Scala (VR) 
		- Cod.Fiscale e P.IVA 01588530236
	</center>

	<table style="width:100%;" >
		<tr class="titoloSezione">
			<td style="padding:0.7em;width:35%;">Cognome e nome:</td>
			<td style="padding:0.7em;width:40%;">Qualifica:</td>
			<td style="padding:0.7em;width:25%;">Assunto dal:</td>
		</tr>
		<tr>
			<td><h2><?php echo $nome; ?></h2></td>
			<td><h3><?php echo $outDipendentiAssunti[$nome]['mansione']; ?></h3></td>
			<td><h3><?php echo $outDipendentiAssunti[$nome]['data assunzione']; ?></h3></td>
		</tr>

	</table>
	
	<br><div class="titoloSezione">Competenze acquisite nei percorsi formativi:</div>

		<?php
		//se non ci sono corsi effettuati lo scrivo e continuo col prossimo
		if (!is_array($daticorsi)){
			echo 'Nessun corso effettuato per il momento.';
			echo "\n<span class='finePagina'></span>";
			//ci mett già anche quello per la seconda pagina che sicuramente non ho utilizzato
			echo "\n<span class='finePagina'></span>";
			continue;
		}
	?><table><?php
			$contacorsi=0;
			foreach ($daticorsi as $corso){
			$contacorsi++;
			if($contacorsi==7){
				?>
				</table>
				<div style="text-align:right;">Continua su pagina 2</div>
				<span class="finePagina"></span>

				<br>
				<div style="text-align:right;">Libretto formativo del dipendente <b><?php echo $nome;?></b></div>
				<br> Continua da pagina 1
				<br><br>
				<table>
				<?php
			}
			?>
				<tr>
					<td rowspan="6" class="dataCorso">
						<?php echo $corso['DATA FINE'];?>
					</td>						
					<td colspan="2" class="titoloCorso">
						<b><?php echo $corso['DESCRIZIONE CORSO'];?></b>
					</td>
				</tr>
				<tr><td style="width:12em;">TIPO</td><td> 			<?php echo $corso['TIPO CORSO'];?></td></tr>
				<tr><td>RIF.NORMATIVO</td><td> 	<?php echo $corso['RIFERIMENTO NORMATIVO'];?></td></tr>
				<tr><td>DURATA ORE</td><td> 	<?php echo $corso['DURATA ORE'];?></td></tr>
				<tr><td>ENTE</td><td> 			<?php echo $corso['ENTE ORGANIZZATORE'];?></td></tr>
				<tr><td>VALIDITA'</td><td> 		<?php echo $corso['VALIDITA ANNI'];?></td></tr>
			<?php
			}
		?>
	</table>
	<span class="finePagina"></span>

	<?php
	// se non ho utilizzato la seconda pagina aggiungo una pagina vuota così posso stampare fronte e retro.
	if($contacorsi<7){
		echo '<span class="finePagina"></span>';
	}
}


echo $outTxt;
?>
